name: Build page
on:
  push:
    branches: [ "v1cleanup" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Set up Node
      uses: actions/setup-node@v2
    - name: Rollup build
      run: cd static/_js && npm install . && npm install -g rollup && rollup -c
    - name: Install deps
      run: go mod download
    - name: Build and install
      run: go build -o main .
    - name: dist
      run: ./main -p 0 -o dist .
    - name: add robots.txt
      run: "printf 'User-agent: *\nDisallow: /\n' > ./dist/robots.txt"
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: dist
        repo: docgo/docgo.github.io
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
