name: Build page
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Install deps
      run: go mod download
    - name: Build and install
      run: go install .
    - name: dist
      run: docgo -p 0 .
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    
